version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - "8080:3000"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongodb:27017/booking_app
    networks:
      - app-network

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
